#!/usr/bin/env python3
"""vsbackup main file."""

import vsb_argparser
import vsb_consts as consts
import vsb_backup as backup
import vsb_utils as utils
import vsb_restore as restore


if __name__ == '__main__':
    settings = utils.loadJsonFile(consts.json_settings)
    print("Settings loaded from", consts.json_settings, " :", settings)

    settings = vsb_argparser.parseArgs(settings)
    print("Settings configured from args:", settings)

    sections = utils.loadJsonFile(settings['backuplist'])
    print("Sections loaded from", settings['backuplist'], " :", settings)

    if settings['backup']:
        utils.clearTmp(settings, sections)
        backup.backupSections(settings, sections)
        backup.backupList(settings)
        buname = backup.genBackupName(settings)
        utils.compress(utils.tmpBackupDir(settings), buname)
        print('BACKUP CREATED AT', buname)
        print()

    if 'restorefile' in settings.keys():
        utils.untargz(settings['restorefile'], utils.tmpRestoreDir(settings))
        restore.restore(settings)
        print('RESTORATION COMPLETE')
        print()

    utils.permitTmp(settings, sections)
    utils.clearTmp(settings, sections)
